name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
        run:|
          touch .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo GITHUB_SECRET=${{ secrets.GITHUB_SECRET }} >> .env
          echo GITHUB_ID=${{ secrets.GITHUB_ID }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
          echo NEXTAUTH_CALLBACK_URL=${{ secrets.NEXTAUTH_CALLBACK_URL }} >> .env
          echo NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} >> .env
          echo STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} >> .env
          echo NEXT_PUBLIC_STRIPE_SUCCESS_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_STRIPE_SUCCESS_REDIRECT_URL }} >> .env
          echo NEXT_PUBLIC_STRIPE_ERROR_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_STRIPE_ERROR_REDIRECT_URL }} >> .env
          cat .env
    - name: Build the Docker image
      run: docker-compose up -d
